apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  postgres-user: {{ .Values.postgres.auth.username }}
  postgres-password: {{ .Values.postgres.auth.password }}
  postgres-db: {{ .Values.postgres.auth.database }}
  jwt-secret: {{ .Values.jwtSecret | default "iLe7lzdWTrKVNFTxwHr19jccAkk7wnSDli7VXcPYTdNwUtvTEQqQJW9v44G7MWrIPW32XGYzYcBjFbJFE2DbOg==" }}
